name: Deploy MKDocs

on:
  # Déclenche le workflow lors d'un push sur la branche principale (main)
  push:
    branches: ["main"]
  # Permet de déclencher manuellement le workflow depuis l'onglet Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Vérification du code source
      - name: Checkout
        uses: actions/checkout@v4

      # Étape 2: Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Étape 3: Installation des dépendances MKDocs
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs

      # Étape 4: Construction du site MKDocs
      - name: Build site
        run: mkdocs build

      # Étape 5: Déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: site

